import express from 'express'
import { authRunner, authUsuario } from '../middleware/auth.js'
import { actualizarJobDesdeRunner, crearJob, listarJobs, obtenerJob, reclamarSiguiente, validarJob } from '../servicios/jobsServicio.js'
import { consulta } from '../db/pool.js'
import { jobPublico } from '../util/normalizadores.js'
export const jobsRouter=express.Router()
jobsRouter.get('/',authUsuario,async(req,res,next)=>{try{const items=await listarJobs(req.cuenta.gateway_id,req.query); res.json({items,total:items.length,returned:items.length})}catch(e){next(e)}})
jobsRouter.post('/',authUsuario,async(req,res,next)=>{try{res.json({ok:true,job:await crearJob(req.body,req.cuenta.gateway_id)})}catch(e){next(e)}})
jobsRouter.post('/bulk',authUsuario,async(req,res,next)=>{try{if(!Array.isArray(req.body?.jobs)) throw new Error('Body debe tener jobs: []'); const items=[]; for(const j of req.body.jobs) items.push(await crearJob(j,req.cuenta.gateway_id)); res.json({ok:true,items,total:items.length})}catch(e){next(e)}})
jobsRouter.get('/:id',authUsuario,async(req,res,next)=>{try{const job=await obtenerJob(req.cuenta.gateway_id,req.params.id); if(!job) return res.status(404).json({ok:false,error:'Job no encontrado'}); res.json({ok:true,job})}catch(e){next(e)}})

jobsRouter.patch('/:id',authUsuario,async(req,res,next)=>{try{const j=validarJob(req.body,req.cuenta.gateway_id); const {rows}=await consulta(`UPDATE aplicacion.jobs SET tipo=$3, runner_target=$4, payload=$5, prioridad=$6, nota=$7, estado='queued', actualizado_en=now() WHERE gateway_id=$1 AND id=$2 AND estado IN ('queued','cancelled','error','timeout','rejected') RETURNING *`,[req.cuenta.gateway_id,req.params.id,j.tipo,j.runnerTarget,j.payload,j.prioridad,j.nota]); if(!rows[0]) return res.status(404).json({ok:false,error:'Job no editable o no encontrado'}); res.json({ok:true,job:jobPublico(rows[0])})}catch(e){next(e)}})
jobsRouter.post('/:id/cancel',authUsuario,async(req,res,next)=>{try{const {rows}=await consulta(`UPDATE aplicacion.jobs SET estado=CASE WHEN estado IN ('running','needs_approval') THEN 'cancel_requested' ELSE 'cancelled' END, resumen='Cancelación solicitada desde Server-Agent', actualizado_en=now(), terminado_en=CASE WHEN estado NOT IN ('running','needs_approval') THEN now() ELSE terminado_en END WHERE gateway_id=$1 AND id=$2 RETURNING *`,[req.cuenta.gateway_id,req.params.id]); if(!rows[0]) return res.status(404).json({ok:false,error:'Job no encontrado'}); res.json({ok:true,job:jobPublico(rows[0])})}catch(e){next(e)}})
jobsRouter.post('/:id/requeue',authUsuario,async(req,res,next)=>{try{const {rows}=await consulta(`UPDATE aplicacion.jobs SET estado='queued', claimed_by=NULL, iniciado_en=NULL, terminado_en=NULL, exit_code=NULL, error=NULL, resumen='Reencolado manualmente', actualizado_en=now() WHERE gateway_id=$1 AND id=$2 RETURNING *`,[req.cuenta.gateway_id,req.params.id]); if(!rows[0]) return res.status(404).json({ok:false,error:'Job no encontrado'}); res.json({ok:true,job:jobPublico(rows[0])})}catch(e){next(e)}})
jobsRouter.delete('/:id',authUsuario,async(req,res,next)=>{try{const r=await consulta('DELETE FROM aplicacion.jobs WHERE gateway_id=$1 AND id=$2',[req.cuenta.gateway_id,req.params.id]); res.json({ok:true,deleted:r.rowCount>0})}catch(e){next(e)}})

jobsRouter.post('/runner/claim-next',authRunner,async(req,res,next)=>{try{const runnerId=String(req.body?.runnerId||'').trim(); if(!runnerId) throw new Error('runnerId requerido'); res.json({ok:true,job:await reclamarSiguiente(req.cuenta.gateway_id,runnerId)})}catch(e){next(e)}})
jobsRouter.post('/runner/:id/update',authRunner,async(req,res,next)=>{try{const runnerId=String(req.body?.runnerId||'').trim(); if(!runnerId) throw new Error('runnerId requerido'); res.json({ok:true,job:await actualizarJobDesdeRunner(req.cuenta.gateway_id,runnerId,req.params.id,req.body)})}catch(e){next(e)}})
