import { consulta } from '../db/pool.js'
import { jobPublico, TIPOS_JOB_VALIDOS } from '../util/normalizadores.js'
import { limitarTexto, nuevoJobId } from '../util/seguridad.js'
import { env } from '../config/env.js'
export function validarJob(input,gatewayId){ if(!input||typeof input!=='object') throw new Error('Body JSON requerido'); if(!TIPOS_JOB_VALIDOS.has(input.type)) throw new Error(`type inválido: ${input.type}`); if(!input.runnerTarget||typeof input.runnerTarget!=='string') throw new Error('runnerTarget es requerido'); if(!input.payload||typeof input.payload!=='object'||Array.isArray(input.payload)) throw new Error('payload debe ser objeto JSON'); return {id:nuevoJobId(),gatewayId,tipo:input.type,estado:'queued',runnerTarget:input.runnerTarget.trim(),payload:input.payload,prioridad:Number(input.priority||0),nota:input.note?String(input.note):''} }
export async function crearJob(input,gatewayId){ const j=validarJob(input,gatewayId); const {rows}=await consulta(`INSERT INTO aplicacion.jobs(id,gateway_id,tipo,estado,runner_target,payload,prioridad,nota) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`, [j.id,j.gatewayId,j.tipo,j.estado,j.runnerTarget,j.payload,j.prioridad,j.nota]); return jobPublico(rows[0]) }
export async function listarJobs(gatewayId,{limit=20,status='',runnerTarget=''}={}){ const params=[gatewayId]; const where=['gateway_id=$1']; if(status){params.push(status); where.push(`estado=$${params.length}`)} if(runnerTarget){params.push(runnerTarget); where.push(`runner_target=$${params.length}`)} params.push(Math.min(Number(limit||20),100)); const {rows}=await consulta(`SELECT * FROM aplicacion.jobs WHERE ${where.join(' AND ')} ORDER BY actualizado_en DESC LIMIT $${params.length}`,params); return rows.map(r=>jobPublico(r,false)) }
export async function obtenerJob(gatewayId,id){ const {rows}=await consulta('SELECT * FROM aplicacion.jobs WHERE gateway_id=$1 AND id=$2',[gatewayId,id]); return jobPublico(rows[0]) }
export async function reclamarSiguiente(gatewayId,runnerId){ const {rows}=await consulta(`UPDATE aplicacion.jobs SET estado='running', claimed_by=$2, iniciado_en=now(), actualizado_en=now() WHERE id=(SELECT id FROM aplicacion.jobs WHERE gateway_id=$1 AND runner_target=$2 AND estado='queued' ORDER BY prioridad DESC, creado_en ASC LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING *`,[gatewayId,runnerId]); return jobPublico(rows[0]) }
export async function actualizarJobDesdeRunner(gatewayId,runnerId,jobId,body){ const estado=String(body.status||''); const permitidos=new Set(['running','needs_approval','success','error','timeout','cancelled','rejected']); if(!permitidos.has(estado)) throw new Error('status inválido'); const terminal=['success','error','timeout','cancelled','rejected'].includes(estado); const {rows}=await consulta(`UPDATE aplicacion.jobs SET estado=$4, claimed_by=$2, actualizado_en=now(), exit_code=COALESCE($5, exit_code), resumen=COALESCE($6, resumen), error=COALESCE($7, error), stdout_tail=COALESCE($8, stdout_tail), stderr_tail=COALESCE($9, stderr_tail), resultado=COALESCE($10, resultado), truncado=COALESCE($11, truncado), local_log_path=COALESCE($12, local_log_path), needs_approval_at=CASE WHEN $4='needs_approval' THEN now() ELSE needs_approval_at END, terminado_en=CASE WHEN $13 THEN now() ELSE terminado_en END WHERE gateway_id=$1 AND id=$3 AND (runner_target=$2 OR claimed_by=$2) RETURNING *`, [gatewayId,runnerId,jobId,estado,body.exitCode??null,body.summary?limitarTexto(body.summary,2000):null,body.error?limitarTexto(body.error,4000):null,'stdoutTail'in body?limitarTexto(body.stdoutTail,env.maxTailChars):null,'stderrTail'in body?limitarTexto(body.stderrTail,env.maxTailChars):null,'result'in body?body.result:null,'truncated'in body?Boolean(body.truncated):null,body.localLogPath?limitarTexto(body.localLogPath,1000):null,terminal]); if(!rows[0]) throw new Error('Job no encontrado o no pertenece al runner'); return jobPublico(rows[0]) }
